#!/usr/bin/env python3
"""Guard that the shipped Windows app icon is the console's mark (D-016).

`assets/logo/thoughtborne.ico` is generated by `assets/logo/make_app_icon.py` from
`console_ui.LOGO_MARK_A5` and `console_ui.ACCENT`; nothing rebuilds it on its own,
so a change to the mark or the accent would otherwise leave the desktop icon
silently stale. This driver decodes the .ico with the stdlib and holds it to the
spec D-016 states:

  - ten frames, 16 20 24 32 40 48 64 96 128 256 px, 32-bit, ascending;
  - frames up to 64 px stored as bitmaps (Tk's own ICO reader sizes a frame by its
    bitmap header -- a PNG frame reads as garbage and blurs the settings window's
    icon), the larger ones as PNG;
  - every frame pixel-identical to the mark on its 9x8 pixel tile: the 7x6 mark
    plus one ring of ground pixels at one integer scale, hard corners, exactly two
    opaque colours (accent, ground) and full transparency outside -- so no
    anti-aliasing can creep in. At 16 and 24 px the ring is one device pixel and
    the mark takes the next scale (16x14, 23x20), as the generator documents;
  - the bitmap frames' AND masks agree with their alpha (a formal must the loader
    tolerates being wrong, so nothing else would notice);
  - the two consumers -- setup.ps1 (shortcut + DisplayIcon) and the settings
    window -- and the release must-have list name that file.

One case sits outside that spec: *how* the settings window sets the icon (#296).
`default=` reaches only the window class; the taskbar button reads the window's own
icon. So the two iconbitmap calls are not duplicates of each other, and neither may
sit in the try that guards the other -- a fact only the source can be held to
off-Windows, which is why this driver reads it.

    python3 test_app_icon.py           # verify, exit non-zero on failure
    python3 test_app_icon.py --show    # also print each frame as ASCII art

Pure stdlib (struct, zlib), Python 3.10+, off-Windows. The PNG decoder covers what
the generator writes (8-bit RGBA, non-interlaced) and says so if it meets anything
else. Sibling of test_deps_sync.py: a CASES list, PASS/FAIL print, non-zero exit.
"""
import ast
import re
import struct
import sys
import zlib
from pathlib import Path

REPO = Path(__file__).resolve().parent
sys.path.insert(0, str(REPO))
import console_ui  # noqa: E402

SHOW = "--show" in sys.argv
ICO = REPO / "assets" / "logo" / "thoughtborne.ico"
SIZES = (16, 20, 24, 32, 40, 48, 64, 96, 128, 256)
PNG_FROM = 96
GROUND = (0x24, 0x24, 0x24)
PNG_SIG = b"\x89PNG\r\n\x1a\n"


# ======================================================================
# the spec: what each frame must look like, from the console's own mark
# ======================================================================
def decode_mark(rows):
    width = max(len(r) for r in rows)
    bitmap = []
    for r in rows:
        r = r.ljust(width)
        bitmap.append([ch in "█▀" for ch in r])
        bitmap.append([ch in "█▄" for ch in r])
    return bitmap


def accent_rgb():
    m = re.fullmatch(r"38;2;(\d+);(\d+);(\d+)", console_ui.ACCENT)
    assert m, (f"console_ui.ACCENT is {console_ui.ACCENT!r}, not a 24-bit SGR colour -- "
               "the app icon is built from it (D-016); give make_app_icon.py an explicit accent")
    return tuple(int(c) for c in m.groups())


def expected_frame(n):
    """RGBA rows for size n -- the same geometry rule make_app_icon.py documents."""
    mark = decode_mark(console_ui.LOGO_MARK_A5)
    mw, mh = len(mark[0]), len(mark)
    k = n // (mw + 2)
    ring = k
    if (mw + 2) * k < 0.8 * n:
        k, ring = (n - 2) // mw, 1
    tw, th = mw * k + 2 * ring, mh * k + 2 * ring
    x0, y0 = (n - tw) // 2, (n - th) // 2
    accent = accent_rgb() + (255,)
    ground = GROUND + (255,)
    clear = (0, 0, 0, 0)
    rows = [[clear] * n for _ in range(n)]
    for y in range(th):
        for x in range(tw):
            rows[y0 + y][x0 + x] = ground
    for my, row in enumerate(mark):
        for mx, on in enumerate(row):
            if on:
                for dy in range(k):
                    for dx in range(k):
                        rows[y0 + ring + my * k + dy][x0 + ring + mx * k + dx] = accent
    return rows


# ======================================================================
# the file: ICO directory, bitmap frames, PNG frames
# ======================================================================
def read_directory(data):
    reserved, kind, count = struct.unpack_from("<HHH", data, 0)
    assert reserved == 0 and kind == 1, "not an ICO file (header)"
    entries = []
    for i in range(count):
        w, h, colors, res, planes, bits, size, off = struct.unpack_from("<BBBBHHII", data, 6 + 16 * i)
        entries.append(dict(w=w or 256, h=h or 256, planes=planes, bits=bits, size=size, off=off,
                            payload=data[off:off + size]))
    return entries


def decode_bmp(payload, n):
    (bi_size, w, h2, planes, bits, comp) = struct.unpack_from("<IiiHHI", payload, 0)
    assert bi_size == 40 and comp == 0, f"bitmap frame {n}: unexpected BITMAPINFOHEADER"
    assert w == n and h2 == 2 * n and planes == 1 and bits == 32, \
        f"bitmap frame {n}: header says {w}x{h2 // 2} {bits}-bit, expected {n}x{n} 32-bit"
    xor_len = n * n * 4
    xor = payload[40:40 + xor_len]
    mask_row = ((n + 31) // 32) * 4
    mask = payload[40 + xor_len:40 + xor_len + mask_row * n]
    assert len(xor) == xor_len and len(mask) == mask_row * n, f"bitmap frame {n}: truncated"
    rows, masks = [], []
    for y in range(n):
        src = n - 1 - y                      # bottom-up storage
        row = []
        for x in range(n):
            b, g, r, a = xor[(src * n + x) * 4:(src * n + x) * 4 + 4]
            row.append((r, g, b, a))
        rows.append(row)
        mrow = mask[src * mask_row:(src + 1) * mask_row]
        masks.append([bool(mrow[x // 8] & (0x80 >> (x % 8))) for x in range(n)])
    return rows, masks


def decode_png(payload, n):
    assert payload.startswith(PNG_SIG), f"frame {n}: expected a PNG payload"
    pos, idat, ihdr = 8, b"", None
    while pos < len(payload):
        length, ctype = struct.unpack_from(">I4s", payload, pos)
        body = payload[pos + 8:pos + 8 + length]
        if ctype == b"IHDR":
            ihdr = struct.unpack(">IIBBBBB", body)
        elif ctype == b"IDAT":
            idat += body
        pos += 12 + length
    w, h, depth, ctype, _, _, interlace = ihdr
    assert (w, h) == (n, n), f"PNG frame {n}: IHDR says {w}x{h}"
    assert depth == 8 and ctype == 6 and interlace == 0, \
        f"PNG frame {n}: {depth}-bit colour type {ctype} interlace {interlace} -- the decoder here " \
        "covers the generator's 8-bit RGBA; extend it if the generator changed"
    raw = zlib.decompress(idat)
    bpp, stride = 4, n * 4
    prev = bytearray(stride)
    rows = []
    for y in range(n):
        f = raw[y * (stride + 1)]
        line = bytearray(raw[y * (stride + 1) + 1:(y + 1) * (stride + 1)])
        for i in range(stride):
            a = line[i - bpp] if i >= bpp else 0
            b = prev[i]
            c = prev[i - bpp] if i >= bpp else 0
            if f == 1:
                line[i] = (line[i] + a) & 0xFF
            elif f == 2:
                line[i] = (line[i] + b) & 0xFF
            elif f == 3:
                line[i] = (line[i] + (a + b) // 2) & 0xFF
            elif f == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pr = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                line[i] = (line[i] + pr) & 0xFF
            else:
                assert f == 0, f"PNG frame {n}: unknown filter {f}"
        rows.append([tuple(line[x * 4:x * 4 + 4]) for x in range(n)])
        prev = line
    return rows


def decode_frame(entry):
    n = entry["w"]
    if entry["payload"].startswith(PNG_SIG):
        return decode_png(entry["payload"], n), None
    return decode_bmp(entry["payload"], n)


def ascii_art(rows, accent):
    out = []
    for row in rows:
        out.append("".join("#" if px[:3] == accent and px[3] else ("=" if px[3] else ".") for px in row))
    return "\n".join(out)


# ======================================================================
# cases
# ======================================================================
def _entries():
    assert ICO.exists(), f"{ICO.relative_to(REPO)} is missing -- run assets/logo/make_app_icon.py"
    return read_directory(ICO.read_bytes())


def test_accent_is_rgb():
    accent_rgb()


def test_directory():
    entries = _entries()
    sizes = tuple(e["w"] for e in entries)
    assert sizes == SIZES, f"frames are {sizes}, expected {SIZES} (ascending)"
    data_len = ICO.stat().st_size
    for e in entries:
        assert e["h"] == e["w"], f"frame {e['w']}: not square"
        assert e["bits"] == 32 and e["planes"] == 1, f"frame {e['w']}: directory says {e['bits']}-bit"
        assert e["off"] + e["size"] <= data_len, f"frame {e['w']}: payload runs past the file"


def test_frame_formats():
    for e in _entries():
        is_png = e["payload"].startswith(PNG_SIG)
        if e["w"] >= PNG_FROM:
            assert is_png, f"frame {e['w']}: expected PNG"
        else:
            assert not is_png, (f"frame {e['w']}: stored as PNG -- Tk's ICO reader cannot size PNG "
                                "frames and would blur the settings window's icon (D-016)")


def test_frames_match_mark():
    accent = accent_rgb()
    for e in _entries():
        n = e["w"]
        rows, _ = decode_frame(e)
        want = expected_frame(n)
        if SHOW:
            print(f"--- {n} px ---\n{ascii_art(rows, accent)}")
        diff = sum(1 for y in range(n) for x in range(n) if rows[y][x] != want[y][x])
        assert diff == 0, (f"frame {n}: {diff} pixel(s) differ from the mark on its tile -- "
                           "rebuild with assets/logo/make_app_icon.py")
        colours = {px[:3] for row in rows for px in row if px[3]}
        assert colours == {accent, GROUND}, f"frame {n}: opaque colours {sorted(colours)}"
        assert all(px[3] in (0, 255) for row in rows for px in row), f"frame {n}: partial alpha"


def test_bitmap_masks_agree_with_alpha():
    for e in _entries():
        rows, masks = decode_frame(e)
        if masks is None:
            continue
        n = e["w"]
        bad = sum(1 for y in range(n) for x in range(n) if masks[y][x] != (rows[y][x][3] == 0))
        assert bad == 0, f"bitmap frame {n}: AND mask disagrees with alpha in {bad} pixel(s)"


def test_consumers_name_the_file():
    setup = (REPO / "setup.ps1").read_text(encoding="ascii")
    assert setup.count(r"assets\logo\thoughtborne.ico") >= 2, \
        "setup.ps1 must point both the shortcut and DisplayIcon at assets\\logo\\thoughtborne.ico"
    settings = (REPO / "thoughtborne_settings.py").read_text(encoding="utf-8")
    assert '"assets" / "logo" / "thoughtborne.ico"' in settings and "iconbitmap(" in settings, \
        "thoughtborne_settings.py does not load assets/logo/thoughtborne.ico as the window icon"
    release = (REPO / "build-release-zip.sh").read_text(encoding="utf-8")
    assert "assets/logo/thoughtborne.ico" in release, "build-release-zip.sh must-have list lacks the icon"


def test_settings_window_sets_both_icon_forms():
    """Both of Tk's icon routes, neither inside the other's guard, plus the repeat (#296).

    Read as an AST rather than as substrings, so a mention in a comment or a docstring
    cannot stand in for a call."""
    path = REPO / "thoughtborne_settings.py"
    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))

    def is_iconbitmap(node):
        # wm_iconbitmap is the same tkinter method under its other name.
        return (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
                and node.func.attr in ("iconbitmap", "wm_iconbitmap"))

    def form_of(node):
        """"class" for the default= route, "window" for the bitmap one, None for a read."""
        if any(kw.arg == "default" for kw in node.keywords):
            return "class"
        if node.args or any(kw.arg == "bitmap" for kw in node.keywords):
            return "window"
        return None

    found = []   # (call, the try statements guarding it, innermost first)

    def walk(node, guards):
        """Collect every iconbitmap call with the try: bodies it runs inside.

        Only bodies, and only try statements that have an except: a handler, an else
        or a finally is not covered by its own try, and a try/finally catches nothing."""
        if is_iconbitmap(node):
            found.append((node, guards))
        if isinstance(node, ast.Try):
            inner = (node, *guards) if node.handlers else guards
            for stmt in node.body:
                walk(stmt, inner)
            for stmt in [*node.handlers, *node.orelse, *node.finalbody]:
                walk(stmt, guards)
            return
        for child in ast.iter_child_nodes(node):
            walk(child, guards)

    walk(tree, ())
    class_form = [(n, g) for n, g in found if form_of(n) == "class"]
    window_form = [(n, g) for n, g in found if form_of(n) == "window"]
    assert class_form, ("no iconbitmap(default=...) call -- that is the class icon, the "
                        "process-wide one any window carrying none of its own falls back to")
    assert window_form, ("no window-specific iconbitmap(path) call -- that is the one Tk turns "
                         "into WM_SETICON, and the only one the taskbar button reads (#296). It "
                         "writes elsewhere than the default= form, so it is not a duplicate of "
                         "it and must not be tidied away")
    assert all(g for _, g in class_form + window_form), \
        "an iconbitmap call sits outside a try/except -- off Windows it raises and costs the launch"
    for _, outer in class_form:
        for _, inner in window_form:
            assert outer[0] not in inner and inner[0] not in outer, \
                ("an iconbitmap call runs inside the try that guards the other form -- off "
                 "Windows the -default form raises, and the rest of that try's body, the "
                 "window-specific call included, never runs (#296)")

    assert [n for n in ast.walk(tree)
            if isinstance(n, ast.Call) and isinstance(n.func, ast.Attribute)
            and n.func.attr in ("after_idle", "after")
            and any(isinstance(a, ast.Name) and a.id == "_set_window_icon"
                    for a in ast.walk(n))], \
        ("no after/after_idle call hands the window icon back to the running loop -- that "
         "repeat is what keeps the taskbar button off the timing of the shell reaching the "
         "process mid-construction (#296). Repeating it another way is a fair change, but "
         "then this guard is rewritten, not dropped")


CASES = [
    test_accent_is_rgb,
    test_directory,
    test_frame_formats,
    test_frames_match_mark,
    test_bitmap_masks_agree_with_alpha,
    test_consumers_name_the_file,
    test_settings_window_sets_both_icon_forms,
]


def main():
    failures = []
    for case in CASES:
        try:
            case()
            print(f"PASS  {case.__name__}")
        except AssertionError as e:
            failures.append((case.__name__, str(e)))
            print(f"FAIL  {case.__name__}: {e}")
        except Exception as e:  # a crash is also a failure
            failures.append((case.__name__, f"{type(e).__name__}: {e}"))
            print(f"ERROR {case.__name__}: {type(e).__name__}: {e}")
    if failures:
        print(f"\nFAIL: {len(failures)}/{len(CASES)} case(s) failed")
        return 1
    print(f"\nOK: all {len(CASES)} app-icon cases pass -- {len(SIZES)} frames pixel-identical to "
          "console_ui.LOGO_MARK_A5 on its tile, bitmap masks sound, consumers name the file, "
          "settings window sets both icon forms")
    return 0


def test_all():
    """The pytest entry point: the whole driver as one collected test."""
    assert main() == 0


if __name__ == "__main__":
    sys.exit(main())
